version: '3'
services:
  coredns:
    image: coredns/coredns:1.2.5
    restart: always
    command:
      - -conf
      - /etc/coredns/Corefile
    ports:
      - "53:53/udp"
      - "53:53"
    volumes:
      - .:/etc/coredns/

